baseURL = 'https://www.sirinbaklava-augsburg.de'
languageCode = 'de-de'
title = 'Sirin Baklava - Mahmut Usta'
theme = 'ananke'

[menu]
  [[menu.main]]
    name = "Startseite"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Produkte"
    url = "/produkte/"
    weight = 2

  [[menu.main]]
    name = "Über uns"
    url = "/ueber-uns/"
    weight = 3

  [[menu.main]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 4

  [[menu.footer]]
    name = "Impressum"
    url = "/impressum/"
    weight = 1

  [[menu.footer]]
    name = "Datenschutzerklärung"
    url = "/datenschutzerklarung/"
    weight = 2

[params]
  customCSS = ["css/custom.css"]
  custom_css_files = ["css/custom.css"]
[markup.goldmark.renderer]
  unsafe = true

